import React from 'react'

const Home = () => {
    return (
        <div>
            Since December 2019, the world has been in the grip of a contagious virus.<br>
            It was first identified in the city of Wuhan, in China's Hubei province. In the past 10 months,<br>
            this virus has infected over 37 million people, and is responsible for over 1 million deaths globally.<br>
            Governments have imposed strict lockdowns with the aim of reducing the spread<br>
            of the virus, which have had a deep impact on lifestyle, society, and the global economy.<br><br>
            <b>Indeed, it is a watershed for humanity itself, and there is no turning back.</b><br>
        </div>
        
        <div>
        <h2>What is this virus?</h2><br><br>
        <p>COVID-19 is an infectious disease that is caused by a new coronavirus.<br>
            Coronaviruses are a group of viruses that cause respiratory ailments in<br>
            mammals and birds. These ailments can range from mild, like common cold<br>
            in humans, to lethal, such as SARS or MERS. Both SARS and MERS have caused<br>
            epidemics in the 2000s and 2010s. The virus strain that causes COVID-19<br>
            is a variant of SARS, and is called SARS-CoV-2.</p>

        <p>COVID-19 is transmitted through the droplets generated by an infected person<br>
           when they cough, sneeze, or exhale. You can be infected if you breathe in the virus<br>
           due to being in close proximity of an infected person, or by touching your face<br>
           after touching a contaminated surface.</p>
        </div>
        
        <div>
        
        </div>
        
    )
}

export default Home
